# Generated by Django 3.1 on 2021-06-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stocklog_stockname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocklog',
            old_name='type',
            new_name='stock_type',
        ),
    ]
