# Generated by Django 3.1 on 2021-06-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210618_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocklog',
            old_name='stock_type',
            new_name='stock_name',
        ),
        migrations.AddField(
            model_name='stocklog',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
