# Generated by Django 3.1 on 2021-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210618_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklog',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
